# Generated by Django 6.0.6 on 2026-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], default='Cash', max_length=30),
        ),
    ]
