# Generated by Django 6.0.6 on 2026-08-10 04:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_monthlybill_credit_generated_monthlybill_credit_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Next Month Credit'), ('Refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Partially Used', 'Partially Used'), ('Used', 'Used'), ('Completed', 'Completed')], default='Available', max_length=20)),
                ('processed_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_refund', to='mainapp.monthlybill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_refunds', to='mainapp.student')),
                ('target_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_credits', to='mainapp.monthlybill')),
            ],
        ),
    ]
