# Generated by Django 6.0.6 on 2026-08-10 04:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_creditrefund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlybill',
            old_name='credit_generated',
            new_name='extra_paid',
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='credit_status',
            field=models.CharField(choices=[('None', 'None'), ('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Credited', 'Credited'), ('Used', 'Used')], default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='source_bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_refunds', to='mainapp.monthlybill'),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Partially Used', 'Partially Used'), ('Used', 'Used'), ('Completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='transaction_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Refund', 'Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='creditrefund',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
    ]
